/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-04-20 04:36:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/modal1_Adding.jsp", Long.valueOf(1618804626653L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- jquery  -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"resources/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- bootstrap -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/lib/Bootstrap-4-4.1.1/css/bootstrap.min.css\"/>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"resources/lib/Bootstrap-4-4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!--     드롭다운 style -->\r\n");
      out.write("    <style>\r\n");
      out.write("\t.dropbtn {\r\n");
      out.write("\t  background-color: #4CAF50;\r\n");
      out.write("\t  color: white;\r\n");
      out.write("\t  padding: 16px;\r\n");
      out.write("\t  font-size: 16px;\r\n");
      out.write("\t  border: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropdown {\r\n");
      out.write("\t  position: relative;\r\n");
      out.write("\t  display: inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropdown-content {\r\n");
      out.write("\t  display: none;\r\n");
      out.write("\t  position: absolute;\r\n");
      out.write("\t  background-color: #f1f1f1;\r\n");
      out.write("\t  min-width: 160px;\r\n");
      out.write("\t  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("\t  z-index: 1;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropdown-content a {\r\n");
      out.write("\t  color: black;\r\n");
      out.write("\t  padding: 12px 16px;\r\n");
      out.write("\t  text-decoration: none;\r\n");
      out.write("\t  display: block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropdown-content a:hover {background-color: #ddd;}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropdown:hover .dropdown-content {display: block;}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropdown:hover .dropbtn {background-color: #3e8e41;}\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <script>\r\n");
      out.write("\tfunction setData(data){\r\n");
      out.write("\t\tlet dataObjFromMain; //dataObjFromMain.JOB_CD 처럼 접근해서 사용.\r\n");
      out.write("\t\tdataObjFromMain=data;\r\n");
      out.write("\t\tconsole.log('dataObjFromMain',dataObjFromMain); //확인용\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 여기에 DB에 데이터 요청하고 받아오고 view에 적용하는 로직 작성 */\r\n");
      out.write("\t}\r\n");
      out.write("  </script>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!--\r\n");
      out.write("    <h1>In Page</h1>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#exampleModal\" data-whatever=\"@mdo\">담당자 추가</button> \r\n");
      out.write("\t-->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- \t### 담당자 추가 -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t      <div class=\"modal-header\">\r\n");
      out.write("\t        <h5 class=\"modal-title\" id=\"exampleModalLabel\">담당자 추가</h5>\r\n");
      out.write("\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t        </button>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t    <b>최초 지시자&emsp;</b> <em>OOO</em>\r\n");
      out.write("\t\t    &emsp;&emsp;&emsp;&emsp;&emsp;\r\n");
      out.write("\t\t    <b>현재 담당자&emsp;</b> <em>OOO</em>\r\n");
      out.write("\t     \t\r\n");
      out.write("\t     \t<br/><br/>\r\n");
      out.write("\t     \t\r\n");
      out.write("\t\t\t<table>\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr><!--행(row)선언-->\r\n");
      out.write("\t                <th><b>추가 담당자</b></th>\r\n");
      out.write("\t                \t\r\n");
      out.write("\t               \r\n");
      out.write("\t                \t<!-- <input type=\"text\" name = \"UserID\" value=\"\" placeholder = \"담당자 입력\" style=\"width:100px; right:30%;\"/> -->\r\n");
      out.write("\t                \t<!-- <input type=\"text\" class=\"form-control\" id=\"recipient-name\" style=\"width:100px; padding-left:10px\"> -->\r\n");
      out.write("\t                \t<td>\r\n");
      out.write("\t                \t&emsp;\r\n");
      out.write("\t                \t\t<select name=\"solar_birth_yn\" id=\"solar_birth_yn\">\r\n");
      out.write("\t\t                \t\t<option value=\"none\">부 서</option>\r\n");
      out.write("\t\t \t\t\t\t       \t<option value=\"1\">IT</option>\r\n");
      out.write("\t\t\t\t\t       \t \t<option value=\"2\">일반본부</option>\r\n");
      out.write("\t\t\t\t\t   \t\t</select>\r\n");
      out.write("\t\t\t\t\t   \t&emsp;\r\n");
      out.write("\t\t\t\t\t   \t\t<select name=\"solar_birth_yn\" id=\"solar_birth_yn\">\r\n");
      out.write("\t\t                \t\t<option value=\"none\">팀</option>\r\n");
      out.write("\t\t \t\t\t\t       \t<option value=\"1\">계정운영팀</option>\r\n");
      out.write("\t\t\t\t\t       \t \t<option value=\"2\">계정개발팀</option>\r\n");
      out.write("\t\t\t\t\t   \t\t</select>\r\n");
      out.write("\t\t\t\t\t   \t&emsp;\r\n");
      out.write("\t\t\t\t\t   \t\t<select name=\"solar_birth_yn\" id=\"solar_birth_yn\">\r\n");
      out.write("\t\t                \t\t<option value=\"none\">사원</option>\r\n");
      out.write("\t\t \t\t\t\t       \t<option value=\"1\">홍길동</option>\r\n");
      out.write("\t\t\t\t\t       \t \t<option value=\"2\">김동율</option>\r\n");
      out.write("\t\t\t\t\t   \t\t</select>\r\n");
      out.write("\t\t\t\t\t    </td>\r\n");
      out.write("\r\n");
      out.write("\t                <!-- <th rowspan=\"2\"><input type=\"submit\" value=\"로그인\"/></th> -->\r\n");
      out.write("        \t    </tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t      \r\n");
      out.write("\t        <form>\r\n");
      out.write("\t          <div class=\"form-group\">\r\n");
      out.write("\t            <label for=\"recipient-name\" class=\"col-form-label\">제 목</label>\r\n");
      out.write("\t            <input type=\"text\" class=\"form-control\" id=\"recipient-name\">\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t          <div class=\"form-group\">\r\n");
      out.write("\t            <label for=\"message-text\" class=\"col-form-label\">내 용</label>\r\n");
      out.write("\t            <textarea class=\"form-control\" id=\"message-text\" style=\"height:100px\"></textarea>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </form>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <div class=\"modal-footer\">\r\n");
      out.write("\t        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t        <button type=\"button\" class=\"btn btn-primary\">등록</button>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- \t### 지시현황 체크 -->\r\n");
      out.write("\t\t<!-- Button trigger modal -->\r\n");
      out.write("\t<!--  \r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#exampleModalCenter\">\r\n");
      out.write("\t  지시현황\r\n");
      out.write("\t</button>\r\n");
      out.write("\t-->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"exampleModalCenter\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalCenterTitle\" aria-hidden=\"true\">\r\n");
      out.write("\t  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t      <div class=\"modal-header\">\r\n");
      out.write("\t        <h5 class=\"modal-title\" id=\"exampleModalCenterTitle\">지시현황</h5>\r\n");
      out.write("\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t        </button>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t     <table class=\"table\">\r\n");
      out.write("\t\t\t\t <thead>\r\n");
      out.write("\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t      <th>지시자</th>\r\n");
      out.write("\t\t\t\t      <th>담당자</th>\r\n");
      out.write("\t\t\t\t      <th>처리 상태</th>\r\n");
      out.write("   \t\t\t\t      <th>지시 일자</th>\r\n");
      out.write("\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t </thead>\r\n");
      out.write("\t\t\t\t <tbody>\r\n");
      out.write("\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t      <td>John</td>\r\n");
      out.write("\t\t\t\t      <td>Doe</td>\r\n");
      out.write("\t\t\t\t      <td>진행중</td>\r\n");
      out.write("\t\t\t\t      <td>2021.03.01</td>\r\n");
      out.write("\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t      <td>Doe</td>\r\n");
      out.write("\t\t\t\t      <td>Moe</td>\r\n");
      out.write("\t\t\t\t      <td>진행중</td>\r\n");
      out.write("   \t\t\t\t      <td>2021.04.02</td>\r\n");
      out.write("\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t      <td>Moe</td>\r\n");
      out.write("\t\t\t\t      <td>Ryul</td>\r\n");
      out.write("\t\t\t\t      <td>완료</td>\r\n");
      out.write("\t\t\t\t      <td>2021.04.10</td>\r\n");
      out.write("\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t </tbody> \r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <div class=\"modal-footer\">\r\n");
      out.write("\t        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>업무 관리</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- jquery  -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/lib/Bootstrap-4-4.1.1/css/bootstrap.min.css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/lib/Bootstrap-4-4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- datatables -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/lib/DataTables-1.10.24/css/dataTables.bootstrap4.min.css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/lib/DataTables-1.10.24/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/lib/DataTables-1.10.24/js/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t/* 초기 조회 조건 세팅 */\r\n");
      out.write("\t$('#REQUEST_TYPE').val('1'); //구분\r\n");
      out.write("\t$('#BZWR_STS').val('01'); //처리상태\r\n");
      out.write("\t$('#BZWR_DSTC').val('2'); //업무구분\r\n");
      out.write("\t\r\n");
      out.write("\tlet befor7days= new Date();\r\n");
      out.write("\tbefor7days.setDate(befor7days.getDate()-5);\r\n");
      out.write("\tdocument.getElementById('FROM_DATE').valueAsDate = befor7days; //FROM_DATE\r\n");
      out.write("\tdocument.getElementById('TO_DATE').valueAsDate = new Date(); //TO_DATE\r\n");
      out.write("\t\r\n");
      out.write("\t/* 테이블 초기 로딩 */\r\n");
      out.write("\tlet jobList = loadTableData();\r\n");
      out.write("\t\r\n");
      out.write("\t/* 테이블 Index 생성을 위한 함수 */\r\n");
      out.write("\tjobList.on( 'order.dt search.dt', function () {\r\n");
      out.write("\t\tjobList.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {\r\n");
      out.write("\t        cell.innerHTML = i+1;\r\n");
      out.write("\t    } );\r\n");
      out.write("\t} ).draw();\r\n");
      out.write("\r\n");
      out.write("\t/* 테이블 클릭 이벤트  -> 클릭한 row에 해당하는 데이터를 상세 정보에 보여줌*/\r\n");
      out.write("\t$('#job_list tbody').on('click', 'td:nth-child(-n+7)', function () {\r\n");
      out.write("\t\tlet data = jobList.row( this ).data();\r\n");
      out.write("\t    console.log('Table Click Event',data);\r\n");
      out.write("\t   \t\r\n");
      out.write("\t\tif($('#REQUEST_TYPE').val()!='2'){ //\"구분-등록\" 상태면 반응 없음.\r\n");
      out.write("\t        $('#BZWR_INDC_CHGR').text(data.BZWR_INDC_CHGR_TXT); //지시자\r\n");
      out.write("\t        $('#BZWR_EXC_CHGR').text(data.BZWR_EXC_CHGR_TXT); //담당자\r\n");
      out.write("\t        $('#BZWR_STS_2').val(data.BZWR_STS); //처리상태(업무상태)\r\n");
      out.write("\t        $('#BZWR_TTL').val(data.BZWR_TTL); //제목\r\n");
      out.write("\t        $('#BZWR_CNTN').val(data.BZWR_CNTN); //내용 \r\n");
      out.write("\t        if($('#REQUEST_TYPE').val()=='1' || data.BZWR_STS=='02'){\r\n");
      out.write("\t        \t$('#BZWR_EXC_CHGR_BTN').hide();\r\n");
      out.write("\t\t\t\t$('#BZWR_STS_2').attr(\"disabled\",true);\r\n");
      out.write("\t\t\t\t$('#BZWR_TTL').attr(\"disabled\",true);\r\n");
      out.write("\t\t\t\t$('#BZWR_CNTN').attr(\"disabled\",true);\r\n");
      out.write("\t        }else{\r\n");
      out.write("\t        \t$('#BZWR_EXC_CHGR_BTN').show();\r\n");
      out.write("\t\t\t\t$('#BZWR_STS_2').removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t\t$('#BZWR_TTL').removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t\t$('#BZWR_CNTN').removeAttr(\"disabled\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} );\r\n");
      out.write("\r\n");
      out.write("\t/* 선택된  row 하이라이트 */\r\n");
      out.write("\t$('#job_list tbody').on('click', 'tr', function() {\r\n");
      out.write("\t\t$('#job_list tbody > tr').css('background-color','#ffffff');\r\n");
      out.write("\t\t$(this).css('background-color','#f0f5f5');\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t/* 테이블 버튼 이벤트(담당자입력) */\r\n");
      out.write("\t$('#job_list tbody').on( 'click', 'button[name=\"first_btn\"]', function () {\r\n");
      out.write("\t    let data = jobList.row( $(this).parents('tr') ).data();\r\n");
      out.write("\t\t//console.log(\"First Button\",data);\r\n");
      out.write("\t\tsetData(data); //모달 페이지로 데이터를 전달하기 위한 함수\r\n");
      out.write("\t\t$('#exampleModal').modal();\r\n");
      out.write("\t} );\r\n");
      out.write("\r\n");
      out.write("\t/* 테이블 버튼 이벤트(전체진행상황) */\r\n");
      out.write("\t$('#job_list tbody').on( 'click', 'button[name=\"second_btn\"]', function () {\r\n");
      out.write("\t    let data = jobList.row( $(this).parents('tr') ).data();\r\n");
      out.write("\t\t//console.log(\"Second Button\",data);\r\n");
      out.write("\t    setData(data); //모달 페이지로 데이터를 전달하기 위한 함수\r\n");
      out.write("\t\t$('#exampleModalCenter').modal();\r\n");
      out.write("\t} );\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/* 송신버튼 */\r\n");
      out.write("\t$('#action_submit').click(function(){\r\n");
      out.write("\t\tlet dvcd = $('#REQUEST_TYPE').val();\r\n");
      out.write("\t\tif(dvcd=='1'){\r\n");
      out.write("\t\t\tconsole.log('조회');\r\n");
      out.write("\t\t\tloadTableData();\r\n");
      out.write("\t\t}else if(dvcd=='2'){\r\n");
      out.write("\t\t\tconsole.log('등록');\r\n");
      out.write("\t\t\tcreateNewJob();\r\n");
      out.write("\t\t}else if(dvcd=='3'){\r\n");
      out.write("\t\t\tconsole.log('변경');\r\n");
      out.write("\t\t\tupdateJob();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t/* 구분 변경 이벤트 처리 */\r\n");
      out.write("\t$('#REQUEST_TYPE').change(function() {\r\n");
      out.write("\t\tlet dvcd = $('#REQUEST_TYPE').val();\r\n");
      out.write("\t\tif(dvcd=='1'){\r\n");
      out.write("\t\t\t$('#BZWR_EXC_CHGR_BTN').hide();\r\n");
      out.write("\t\t\t$('#BZWR_STS_2').attr(\"disabled\",true);\r\n");
      out.write("\t\t\t$('#BZWR_TTL').attr(\"disabled\",true);\r\n");
      out.write("\t\t\t$('#BZWR_CNTN').attr(\"disabled\",true);\r\n");
      out.write("\t\t}else if(dvcd=='2'){\r\n");
      out.write("\t\t\t$('#BZWR_INDC_CHGR').text('로그인 유저');\r\n");
      out.write("\t\t\t$('#BZWR_EXC_CHGR').text('');\r\n");
      out.write("\t\t\t$('#BZWR_EXC_CHGR_BTN').show();\r\n");
      out.write("\t\t\t$('#BZWR_STS_2').attr(\"disabled\",true);\r\n");
      out.write("\t\t\t$('#BZWR_TTL').val(\"\");\r\n");
      out.write("\t\t\t$('#BZWR_CNTN').val(\"\");\r\n");
      out.write("\t\t\t$('#BZWR_TTL').removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t$('#BZWR_CNTN').removeAttr(\"disabled\");\r\n");
      out.write("\t\t}else if(dvcd=='3'){\r\n");
      out.write("\t\t\t$('#BZWR_EXC_CHGR_BTN').show();\r\n");
      out.write("\t\t\t$('#BZWR_STS_2').removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t$('#BZWR_TTL').removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t$('#BZWR_CNTN').removeAttr(\"disabled\");\r\n");
      out.write("\t\t\talert('변경할 데이터를 선택해주세요.');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("} );\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function loadTableData(){\r\n");
      out.write("\t/* 테이블 데이터 로딩 및 세팅 */\r\n");
      out.write("\tlet sendData = {\r\n");
      out.write("    \t\tREQUEST_TYPE:$('#REQUEST_TYPE').val(),\r\n");
      out.write("    \t\tFROM_DATE:$('#FROM_DATE').val(), \r\n");
      out.write("    \t\tTO_DATE:$('#TO_DATE').val(),\r\n");
      out.write("    \t\tBZWR_STS:$('#BZWR_STS').val(),\r\n");
      out.write("    \t\tBZWR_DSTC:$('#BZWR_DSTC').val()\r\n");
      out.write("    };\r\n");
      out.write("\tconsole.log('sendData',sendData);\r\n");
      out.write("\treturn jobList = $('#job_list').DataTable( {\r\n");
      out.write("        ajax : {\r\n");
      out.write("        \turl : 'resources/lib/testJson2.json',\r\n");
      out.write("        \ttype : 'POST',\r\n");
      out.write("        \tdata : sendData\r\n");
      out.write("        },\r\n");
      out.write("        responsive: true,\r\n");
      out.write("        columns : [\r\n");
      out.write("\t\t\t{data: null },\r\n");
      out.write("\t\t\t{data: \"BZWR_TTL\" },\r\n");
      out.write("            {data: \"BZWR_STS\", render : function ( data, type, row, meta ) {\r\n");
      out.write("            \tif(data==\"01\"){\r\n");
      out.write("            \t\treturn '진행중';\r\n");
      out.write("            \t}else if(data==\"02\"){\r\n");
      out.write("            \t\treturn '완료';\r\n");
      out.write("            \t}\r\n");
      out.write("            }},\r\n");
      out.write("            {data: \"BZWR_INDC_CHGR_TXT\" },\r\n");
      out.write("            {data: \"BZWR_EXC_CHGR_TXT\" },\r\n");
      out.write("            {data: \"BZWR_REG_DT\" },\r\n");
      out.write("            {data: \"BZWR_CMPL_DT\" },\r\n");
      out.write("            {data: null , render : function ( data, type, row, meta ) {\r\n");
      out.write("                return '<button name=\"first_btn\" class=\"btn btn-sm btn-default\">입력</button>'\r\n");
      out.write("            }},\r\n");
      out.write("            {data: null , render : function ( data, type, row, meta ) {\r\n");
      out.write("                return '<button name=\"second_btn\" class=\"btn btn-sm btn-default\">확인</button>'\r\n");
      out.write("            }}\r\n");
      out.write("        ],\r\n");
      out.write("        columnDefs: [{ className: 'text-center', targets: [0,2,3,4,5,6,7,8] }],\r\n");
      out.write("        order: [[ 1, 'asc' ]]\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("/* 등록 */\r\n");
      out.write("function createNewJob(){\r\n");
      out.write("\tlet sendData = { \r\n");
      out.write("\t\t\tREQUEST_TYPE:$('#REQUEST_TYPE').val(), //구분(조회,등록,변경)\r\n");
      out.write("\t\t\tBZWR_DSTC:$('#BZWR_DSTC').val(), //업무구분\r\n");
      out.write("\t\t\tBZWR_INDC_CHGR:'로그인 유저', //업무지시담당자\r\n");
      out.write("\t\t\tBZWR_EXC_CHGR:'담당자', //업무수행담당자\r\n");
      out.write("\t\t\tBZWR_STS:'1', //업무상태 (등록 시 진행으로 세팅)\r\n");
      out.write("\t\t\tBZWR_TTL:$('#BZWR_TTL').val(), //업무제목\r\n");
      out.write("\t\t\tBZWR_CNTN:$('#BZWR_CNTN').val() //업무내용\r\n");
      out.write("\t\t};\r\n");
      out.write("\tconsole.log('sendData',sendData);\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl:'',\r\n");
      out.write("\t\tdataType:'application/json',\r\n");
      out.write("\t\tdata : sendData,\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\talert('등록 되었습니다.');\r\n");
      out.write("\t   }\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 변경 */\r\n");
      out.write("function updateJob(){\r\n");
      out.write("\tlet sendData = { \r\n");
      out.write("\t\t\tREQUEST_TYPE:$('#REQUEST_TYPE').val(), //구분(조회,등록,변경)\r\n");
      out.write("\t\t\tBZWR_DSTC:$('#BZWR_DSTC').val(), //업무구분\r\n");
      out.write("\t\t\tBZWR_EXC_CHGR:'담당자', //업무수행담당자\r\n");
      out.write("\t\t\tBZWR_STS:$('#BZWR_STS_2').val(), //업무상태\r\n");
      out.write("\t\t\tBZWR_TTL:$('#BZWR_TTL').val(), //업무제목\r\n");
      out.write("\t\t\tBZWR_CNTN:$('#BZWR_CNTN').val() //업무내용\r\n");
      out.write("\t\t};\r\n");
      out.write("\tconsole.log('sendData',sendData);\r\n");
      out.write("\tif(sendData.BZWR_STS=='02'){ //완료된 업무인 경우 변경 불가\r\n");
      out.write("\t\talert('이미 완료된 업무입니다.');\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:'',\r\n");
      out.write("\t\t\tdataType:'application/json',\r\n");
      out.write("\t\t\tdata : sendData,\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\talert('변경 되었습니다.');\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"container\" style=\"margin-top:30px\">\r\n");
      out.write("\t<!-- 조회 조건 -->\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label style=\"font-weight:bold;\">구분&nbsp;</label>\r\n");
      out.write("\t\t\t<select id=\"REQUEST_TYPE\" style=\"margin-right:25px\">\r\n");
      out.write("\t\t\t    <option value=\"1\">조회</option>\r\n");
      out.write("\t\t\t    <option value=\"2\">등록</option>\r\n");
      out.write("\t\t\t    <option value=\"3\">변경</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<label style=\"font-weight:bold\">조회기간&nbsp;</label>\r\n");
      out.write("\t\t\t<input type=\"date\" id=\"FROM_DATE\" style=\"width:145px\" value=\"\"/>\r\n");
      out.write("\t\t\t<label style=\"font-weight:bold\">~&nbsp;</label>\r\n");
      out.write("\t\t\t<input type=\"date\" id=\"TO_DATE\" value=\"\"  style=\"margin-right:25px;width:145px\"/>\r\n");
      out.write("\t\t\t<label style=\"font-weight:bold;\">처리상태&nbsp;</label>\r\n");
      out.write("\t\t\t<select id=\"BZWR_STS\" style=\"margin-right:25px\">\r\n");
      out.write("\t\t\t    <option value=\"01\">진행</option>\r\n");
      out.write("\t\t\t    <option value=\"02\">완료</option>\r\n");
      out.write("\t\t\t    <option value=\"03\">전체</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<label style=\"font-weight:bold;\">업무구분&nbsp;</label>\r\n");
      out.write("\t\t\t<select id=\"BZWR_DSTC\">\r\n");
      out.write("\t\t\t    <option value=\"1\">지시업무</option>\r\n");
      out.write("\t\t\t    <option value=\"2\">담당업무</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<input type='button' id=\"action_submit\" class=\"btn btn-sm btn-primary\" style=\"float:right\" value='송신'/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr/>\r\n");
      out.write("\t<!-- 목록 -->\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<table id=\"job_list\" class=\"table table-sm responsive table-bordered\" width=\"100%\">\r\n");
      out.write("\t        <thead>\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t            \t<th>No</th>\r\n");
      out.write("\t                <th>제목</th>\r\n");
      out.write("\t                <th>처리상태</th>\r\n");
      out.write("\t                <th>지시자</th>\r\n");
      out.write("\t                <th>담당자</th>\r\n");
      out.write("\t                <th>등록일자</th>\r\n");
      out.write("\t                <th>완료일자</th>\r\n");
      out.write("\t                <th>담당자입력</th>\r\n");
      out.write("\t                <th>전체진행상황</th>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t        </thead>\r\n");
      out.write("\t    </table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<hr/>\r\n");
      out.write("\t<!-- 상세 -->\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<table class=\"table table-bordered table-sm display nowrap\" style=\"text-align:center;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th scope=\"col\" width=\"10%\">지시자</th>\r\n");
      out.write("\t\t\t\t<td scope=\"col\" id=\"BZWR_INDC_CHGR\" width=\"10%\"></td>\r\n");
      out.write("\t\t\t\t<th scope=\"col\" width=\"10%\">담당자</th>\r\n");
      out.write("\t\t\t\t<td scope=\"col\" width=\"10%\">\r\n");
      out.write("\t\t\t\t\t<span id=\"BZWR_EXC_CHGR\"></span>\r\n");
      out.write("\t\t\t\t\t<button id=\"BZWR_EXC_CHGR_BTN\" class=\"btn btn-sm btn-info\" style=\"display:none\">선택</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<th scope=\"col\" width=\"10%\">처리상태</th>\r\n");
      out.write("\t\t\t\t<td scope=\"col\" width=\"10%\">\r\n");
      out.write("\t\t\t\t\t<select id=\"BZWR_STS_2\" class=\"form-control\" disabled>\r\n");
      out.write("\t\t\t\t\t    <option value=\"01\">진행중</option>\r\n");
      out.write("\t\t\t\t\t    <option value=\"02\">완료</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td scope=\"col\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th scope=\"row\">제목</th><td colspan=\"6\"><input type=\"text\" id=\"BZWR_TTL\" class=\"form-control input-sm\" disabled/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th scope=\"row\">내용</th><td colspan=\"6\"><textarea ID=\"BZWR_CNTN\" class=\"form-control input-sm\" rows=\"5\" disabled></textarea></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
