/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-04-15 05:55:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class modal1_005fAdding_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- jquery  -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- bootstrap -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"lib/Bootstrap-4-4.1.1/css/bootstrap.min.css\"/>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"lib/Bootstrap-4-4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("    <title>Modal</title>\r\n");
      out.write("    \r\n");
      out.write("<!--     드롭다운 style -->\r\n");
      out.write("    <style>\r\n");
      out.write("\t.dropbtn {\r\n");
      out.write("\t  background-color: #4CAF50;\r\n");
      out.write("\t  color: white;\r\n");
      out.write("\t  padding: 16px;\r\n");
      out.write("\t  font-size: 16px;\r\n");
      out.write("\t  border: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropdown {\r\n");
      out.write("\t  position: relative;\r\n");
      out.write("\t  display: inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropdown-content {\r\n");
      out.write("\t  display: none;\r\n");
      out.write("\t  position: absolute;\r\n");
      out.write("\t  background-color: #f1f1f1;\r\n");
      out.write("\t  min-width: 160px;\r\n");
      out.write("\t  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\r\n");
      out.write("\t  z-index: 1;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropdown-content a {\r\n");
      out.write("\t  color: black;\r\n");
      out.write("\t  padding: 12px 16px;\r\n");
      out.write("\t  text-decoration: none;\r\n");
      out.write("\t  display: block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropdown-content a:hover {background-color: #ddd;}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropdown:hover .dropdown-content {display: block;}\r\n");
      out.write("\t\r\n");
      out.write("\t.dropdown:hover .dropbtn {background-color: #3e8e41;}\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <h1>In Page</h1>\r\n");
      out.write("\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#exampleModal\" data-whatever=\"@mdo\">담당자 추가</button>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- \t### 담당자 추가 -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t      <div class=\"modal-header\">\r\n");
      out.write("\t        <h5 class=\"modal-title\" id=\"exampleModalLabel\">담당자 추가</h5>\r\n");
      out.write("\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t        </button>\r\n");
      out.write("\t       \r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      \r\n");
      out.write("\t      \r\n");
      out.write("\t      \r\n");
      out.write("\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t    <b>최초 지시자&emsp;</b> <em>OOO</em>\r\n");
      out.write("\t\t    &emsp;&emsp;&emsp;&emsp;&emsp;\r\n");
      out.write("\t\t    <b>현재 담당자&emsp;</b> <em>OOO</em>\r\n");
      out.write("\t     \t\r\n");
      out.write("\t     \t<br/><br/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table>\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr><!--행(row)선언-->\r\n");
      out.write("\t                <th ><b>추가 담당자</b></th>\r\n");
      out.write("\t                \t\r\n");
      out.write("\t               \r\n");
      out.write("\t                \t<!-- <input type=\"text\" name = \"UserID\" value=\"\" placeholder = \"담당자 입력\" style=\"width:100px; right:30%;\"/> -->\r\n");
      out.write("\t                \t<!-- <input type=\"text\" class=\"form-control\" id=\"recipient-name\" style=\"width:100px; padding-left:10px\"> -->\r\n");
      out.write("\t                \t<td>\r\n");
      out.write("\t                \t&emsp;\r\n");
      out.write("\t                \t\t<select name=\"solar_birth_yn\" id=\"solar_birth_yn\">\r\n");
      out.write("\t\t                \t\t<option value=\"none\">부 서</option>\r\n");
      out.write("\t\t \t\t\t\t       \t<option value=\"1\">IT</option>\r\n");
      out.write("\t\t\t\t\t       \t \t<option value=\"2\">일반본부</option>\r\n");
      out.write("\t\t\t\t\t   \t\t</select>\r\n");
      out.write("\t\t\t\t\t   \t&emsp;\r\n");
      out.write("\t\t\t\t\t   \t\t<select name=\"solar_birth_yn\" id=\"solar_birth_yn\">\r\n");
      out.write("\t\t                \t\t<option value=\"none\">팀</option>\r\n");
      out.write("\t\t \t\t\t\t       \t<option value=\"1\">계정운영팀</option>\r\n");
      out.write("\t\t\t\t\t       \t \t<option value=\"2\">계정개발팀</option>\r\n");
      out.write("\t\t\t\t\t   \t\t</select>\r\n");
      out.write("\t\t\t\t\t   \t&emsp;\r\n");
      out.write("\t\t\t\t\t   \t\t<select name=\"solar_birth_yn\" id=\"solar_birth_yn\">\r\n");
      out.write("\t\t                \t\t<option value=\"none\">사원</option>\r\n");
      out.write("\t\t \t\t\t\t       \t<option value=\"1\">홍길동</option>\r\n");
      out.write("\t\t\t\t\t       \t \t<option value=\"2\">김동율</option>\r\n");
      out.write("\t\t\t\t\t   \t\t</select>\r\n");
      out.write("\t\t\t\t\t    </td>\r\n");
      out.write("\r\n");
      out.write("\t                <!-- <th rowspan=\"2\"><input type=\"submit\" value=\"로그인\"/></th> -->\r\n");
      out.write("        \t    </tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t      \r\n");
      out.write("\t        <form>\r\n");
      out.write("\t          <div class=\"form-group\">\r\n");
      out.write("\t            <label for=\"recipient-name\" class=\"col-form-label\">제 목</label>\r\n");
      out.write("\t            <input type=\"text\" class=\"form-control\" id=\"recipient-name\">\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t          <div class=\"form-group\">\r\n");
      out.write("\t            <label for=\"message-text\" class=\"col-form-label\">내 용</label>\r\n");
      out.write("\t            <textarea class=\"form-control\" id=\"message-text\" style=\"height:100px\"></textarea>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </form>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <div class=\"modal-footer\">\r\n");
      out.write("\t        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t        <button type=\"button\" class=\"btn btn-primary\">등록</button>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- \t### 지시현황 체크 -->\r\n");
      out.write("\t\t<!-- Button trigger modal -->\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#exampleModalCenter\">\r\n");
      out.write("\t  지시현황\r\n");
      out.write("\t</button>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"exampleModalCenter\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalCenterTitle\" aria-hidden=\"true\">\r\n");
      out.write("\t  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t      <div class=\"modal-header\">\r\n");
      out.write("\t        <h5 class=\"modal-title\" id=\"exampleModalCenterTitle\">지시현황</h5>\r\n");
      out.write("\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t        </button>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t     <table class=\"table\">\r\n");
      out.write("\t\t\t\t <thead>\r\n");
      out.write("\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t      <th>지시자</th>\r\n");
      out.write("\t\t\t\t      <th>담당자</th>\r\n");
      out.write("\t\t\t\t      <th>처리 상태</th>\r\n");
      out.write("   \t\t\t\t      <th>지시 일자</th>\r\n");
      out.write("\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t </thead>\r\n");
      out.write("\t\t\t\t <tbody>\r\n");
      out.write("\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t      <td>John</td>\r\n");
      out.write("\t\t\t\t      <td>Doe</td>\r\n");
      out.write("\t\t\t\t      <td>진행중</td>\r\n");
      out.write("\t\t\t\t      <td>2021.03.01</td>\r\n");
      out.write("\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t      <td>Doe</td>\r\n");
      out.write("\t\t\t\t      <td>Moe</td>\r\n");
      out.write("\t\t\t\t      <td>진행중</td>\r\n");
      out.write("   \t\t\t\t      <td>2021.04.02</td>\r\n");
      out.write("\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t   <tr>\r\n");
      out.write("\t\t\t\t      <td>Moe</td>\r\n");
      out.write("\t\t\t\t      <td>Ryul</td>\r\n");
      out.write("\t\t\t\t      <td>완료</td>\r\n");
      out.write("\t\t\t\t      <td>2021.04.10</td>\r\n");
      out.write("\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t </tbody> \r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <div class=\"modal-footer\">\r\n");
      out.write("\t        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
